#!/usr/bin/python3

#Problem 2 - Even Fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

currentnum=1
prevnum=0
fibsum=0
limitval=4000000
while currentnum<limitval:
    nextnum=currentnum+prevnum
    prevnum=currentnum
    currentnum=nextnum
    if(currentnum%2==0 and currentnum<limitval):
        fibsum+=currentnum
    print(str(currentnum))

print ("Sum: "+str(fibsum))
    

